name: Daily Oura Telegram Report

on:
  schedule:
    # runs every day at 05 UTC (7 00 AM)
    - cron: '0 5 * * *'
  workflow_dispatch: 

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: pnpm install

      - name: Run pipeline script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          OURA_PERSONAL_TOKEN: ${{ secrets.OURA_PERSONAL_TOKEN }}
        run: node prueba.js
